name: Build EXE for Windows 7

on:
  push:
    branches:
      - main  # Runs on every push to the main branch

jobs:
  build:
    runs-on: windows-latest  # Uses Windows virtual machine for building

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout the repository code
        
      - name: Set up Python
        uses: actions/setup-python@v4  # Sets up Python for the workflow
        with:
          python-version: 3.7  # Compatible with Windows 7

      - name: Install dependencies
        run: |
          pip install pandas
          pip install tabulate
          pip install tk
          pip install pyinstaller
          pip install jalali-pandas

      - name: Build EXE
        run: |
          pyinstaller --onefile --noconsole --distpath ./output final_lab_data_process.py  # Uses your script name

      - name: Upload EXE as artifact
        uses: actions/upload-artifact@v3
        with:
          name: compiled-exe
          path: ./output/*.exe  # Uploads the built executable
