name: Build EXE for Windows 7 (32-bit)

on:
  push:
    branches:
      - main  # Runs on every push to the main branch

jobs:
  build:
    runs-on: windows-2016  # Compatible with older Windows versions

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout the repository code
        
      - name: Set up Python (32-bit)
        uses: actions/setup-python@v4
        with:
          python-version: 3.7.9  # Final Python 3.7 version supporting Windows 7
          architecture: x86  # 32-bit architecture

      - name: Install dependencies
        run: |
          pip install pandas
          pip install tabulate
          pip install tk
          pip install pyinstaller
          pip install jalali-pandas

      - name: Build EXE for 32-bit
        run: |
          pyinstaller --onefile --distpath ./output final_lab_data_process.py  # Replace with your script name

      - name: Upload EXE as artifact
        uses: actions/upload-artifact@v3
        with:
          name: compiled-exe
          path: ./output/*.exe  # Uploads the built executable
