name: Build EXE

on:
  push:
    branches:
      - main # Runs on every push to the main branch

jobs:
  build:
    runs-on: windows-latest # This tells GitHub Actions to use a Windows runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # This checks out your repository's code
        
      - name: Set up Python
        uses: actions/setup-python@v4 # Sets up Python for the workflow
        with:
          python-version: 3.8.15 # Specify the Python version you want to use

      - name: Install dependencies
        run: |
          pip install pyinstaller # Install pyinstaller to convert .py to .exe

      - name: Build EXE
        run: |
          pyinstaller --noconfirm --onefile --windowed --distpath ./final_lab_data_process.py # Builds the .exe file

      - name: Upload EXE as artifact
        uses: actions/upload-artifact@v3
        with:
          name: compiled-exe
          path: ./output/lab_data_process.exe # Specify the location of the generated .exe file
